### ISSUE TITLE
Group monitor shows only 100%

### ISSUE THREAD

**Issue by eberlepatric** [louislam/uptime-kuma#3629]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have different group of monitor, e.g. VoIP. The 3 monitors inside have uptimes around 99.x%, but the monitor shows always only 100%? 

### 👟 Reproduction steps

see picture
<img width="1674" alt="Bildschirmfoto 2023-08-22 um 07 11 47" src="https://github.com/louislam/uptime-kuma/assets/4689293/0c3c00a7-7336-4a8f-972f-f7d5e7023bd6">

### 👀 Expected behavior

For my understanding, the monitor should shows the mean uptime (statistical average) of the 3 monitors inside

### 😓 Actual Behavior

Monitor Groups shows alwyas and only 100%

### 🐻 Uptime-Kuma Version

1.23.0

### 💻 Operating System and Arch

Synology DSM 7.2-64570 Update 3 with Docker

### 🌐 Browser

Firefox 116.0.3

### 🐋 Docker Version

20.10.23 (API: 1.41) and Portainer 2.18.4

**Comment by eberlepatric** [comment]
<img width="995" alt="Bildschirmfoto 2023-08-27 um 21 40 34" src="https://github.com/louislam/uptime-kuma/assets/4689293/7b1fecd3-93c1-4794-9756-3ac57b522cbb">

**Comment by eberlepatric** [comment]
now it works :-) thanks

**Comment by investlab** [comment]
Same problem in  Uptime-Kuma Version 1.23.4

**Comment by chakflying** [comment]
- You are recommended to upgrade to the latest version of `1.23.11` since we have pushed important security and bug fixes.
- I think a more accurate description would be that this is "by design", and a current limitation of the implementation. Remember that the group monitor is just another monitor, it is not synchronized to the children. Depending on the timings and intervals of the children, they may record a downtime without the parent knowing. Improving on this would most likely require major changes to how the feature works.

**Comment by investlab** [comment]
> * You are recommended to upgrade to the latest version of `1.23.11` since we have pushed important security and bug fixes.
> * I think a more accurate description would be that this is "by design", and a current limitation of the implementation. Remember that the group monitor is just another monitor, it is not synchronized to the children. Depending on the timings and intervals of the children, they may record a downtime without the parent knowing. Improving on this would most likely require major changes to how the feature works.
> * If however, you see a large discrepancy between the group and a child, this is most likely a bug, and feel free to create a new issue with details.

![Screenshot_5](https://github.com/louislam/uptime-kuma/assets/10806362/9be757aa-4d71-4bc5-8edc-c534cf2f31b7)
I have updated to version 1.23.11 but the issue still persists.
The 2 monitors inside have uptimes 0% and 100% but the Group monitor shows always only 33.33%. It is not Average?

**Comment by chakflying** [comment]
It is not calculated as an average. For each heartbeat, the group monitor checks if ALL of it children are up. A downtime is recorded if **any** of its child monitor is down.
