### ISSUE TITLE
uv_gettimeofday failed

### ISSUE THREAD

**Issue by mitchplze** [louislam/uptime-kuma#372]
**Is it a duplicate question?**
No

**Describe the bug**
The latest Docker image does not startup anymore, when following instructions or running manually in a docker-compose.yml. I see the following log entry repeated, and the container never launches. I have recreated the data volume, and redownloaded the image - still not working. 

**To Reproduce**
1. Follow Github instructions to run image
2. Image does not launch, and throws error

**Info**
- Uptime Kuma Version: sha256:efbf52d0a4d5a4ab6c4e42b035dac8e3d90ae6586edd3c9d1c75e4dd4ab9361b
- Using Docker?: **Yes**/No
- OS: Raspbian
- Browser: Safari (different computer)

**Screenshots**

**Error Log**

`Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion (0) == (uv_gettimeofday(&tv))' failed.`

**Comment by louislam** [comment]
https://hub.docker.com/repository/docker/louislam/uptime-kuma/tags?page=1&ordering=last_updated

`efbf52d` I cannot find this version. It could be a corrupted image, try to repull it.

**Comment by mitchplze** [comment]
Still not working for me unfortunately. I deleted everything, restarted the Docker host, and repulled. Still the same error: 

![Screen Shot 2021-09-10 at 10 09 14](https://user-images.githubusercontent.com/25162574/132891533-cde22dea-e0a9-4b8a-9444-1075f0a2536b.png)
<img width="1135" alt="Screen Shot 2021-09-10 at 10 09 36" src="https://user-images.githubusercontent.com/25162574/132891635-e8a4681c-c563-41c4-ba85-f0fa2cd80c0b.png">
<img width="767" alt="Screen Shot 2021-09-10 at 10 09 49" src="https://user-images.githubusercontent.com/25162574/132891653-ec80297c-3089-482a-9f6a-c4c677f7f86f.png">
<img width="954" alt="Screen Shot 2021-09-10 at 10 10 00" src="https://user-images.githubusercontent.com/25162574/132891659-56a01173-4066-47b9-acc9-8586f8640dab.png">

**Comment by volcan96** [comment]
Same problem on RPIv4 running raspbian OS. I ended up installing on MacOS docker and works correctly there.

**Comment by louislam** [comment]
Could you try this `uptime-kuma:1-alpine`

**Comment by mitchplze** [comment]
> Could you try this `uptime-kuma:1-alpine`

This image works for me! ✅

FYI I am on Raspbian 10.

**Comment by louislam** [comment]
Ar, Docker is too funny. I wanna cry.

**Comment by volcan96** [comment]
That image seems to have worked. I was able to  start from scratch; haven't tried from an existing installation though

**Comment by louislam** [comment]
My Pi4 is not yet arrived. I think it may be Nodejs problem again. Could you help me to test these commands:

```
docker run --rm node:14-bullseye-slim -e "console.log('hello-world')"
```

```
docker run --rm node:14-buster-slim -e "console.log('hello-world')"
```

```
docker run --rm node:14-stretch-slim -e "console.log('hello-world')"
```

all should output `hello-world`

**Comment by mitchplze** [comment]
Here you go!

First one didn't work, but the other two did.

![Screen Shot 2021-09-10 at 10 55 07](https://user-images.githubusercontent.com/25162574/132897048-e23bfc3d-50fe-4dc7-a178-a35bea102306.png)

![Screen Shot 2021-09-10 at 10 56 39](https://user-images.githubusercontent.com/25162574/132897057-611204f9-de57-4608-a1ec-0e5cb527bc8b.png)

![Screen Shot 2021-09-10 at 10 58 14](https://user-images.githubusercontent.com/25162574/132897185-321dbf1f-1962-41b1-9c97-68ddffd29423.png)

**Comment by louislam** [comment]
> Here you go!
> 
> First one didn't work, but the other two did.
> 
> ![Screen Shot 2021-09-10 at 10 55 07](https://user-images.githubusercontent.com/25162574/132897048-e23bfc3d-50fe-4dc7-a178-a35bea102306.png)
> 
> ![Screen Shot 2021-09-10 at 10 56 39](https://user-images.githubusercontent.com/25162574/132897057-611204f9-de57-4608-a1ec-0e5cb527bc8b.png)
> 
> ![Screen Shot 2021-09-10 at 10 58 14](https://user-images.githubusercontent.com/25162574/132897185-321dbf1f-1962-41b1-9c97-68ddffd29423.png)

Big thanks, I am going to change to buster-slim.

**Comment by louislam** [comment]
`uptime-kuma:1.6.1` should be fixed.

**Comment by volcan96** [comment]
hmmm...Can someone test this? Maybe a docker image caching issue? Pointing to alpine image works; pointing to general image results in same error.

Still seeing the same issue if using the docker-compose below pointing to `image: louislam/uptime-kuma:1`

```
version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/pi/uptime/config/:/app/data
    ports:
      - 3061:3001
```
output: 

```
pi@rpi4:~/uptime $ sudo docker-compose up  --force-recreate --remove-orphans 
Pulling uptime-kuma (louislam/uptime-kuma:1)...
1: Pulling from louislam/uptime-kuma
9bd46ffb253d: Pull complete
910172766907: Pull complete
e1258559d748: Pull complete
00f684fdd258: Pull complete
094c4561a017: Pull complete
6504d4e99899: Pull complete
8ee6fe87d16a: Pull complete
76742278e5ff: Pull complete
Digest: sha256:917800118552877435aeee12c5bfb90a39b8acf2d0e053183883bf4d87bae13e
Status: Downloaded newer image for louislam/uptime-kuma:1
Creating uptime-kuma ... done
Attaching to uptime-kuma
uptime-kuma    | Node.js[1]: ../src/util.cc:188:double node::GetCurrentTimeInMicroseconds(): Assertion `(0) == (uv_gettimeofday(&tv))' failed.
uptime-kuma exited with code 132
```

but if I point to the alpine image it seems to work:

```
version: '3.3'

services:
  uptime-kuma:
# image for testing 1.6
    image: louislam/uptime-kuma:1-alpine
    container_name: uptime-kuma
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /home/pi/uptime/config/:/app/data
    ports:
      - 3061:3001
```
Output:
```
Status: Downloaded newer image for louislam/uptime-kuma:1-alpine
Recreating uptime-kuma ... done
Attaching to uptime-kuma
uptime-kuma    | Welcome to Uptime Kuma
uptime-kuma    | Node Env: undefined
uptime-kuma    | Importing Node libraries
uptime-kuma    | Importing 3rd-party libraries
uptime-kuma    | Importing this project modules
uptime-kuma    | Prepare Notification Providers
uptime-kuma    | Version: 1.6.0
uptime-kuma    | Data Dir: ./data/
uptime-kuma    | Creating express and socket.io instance
uptime-kuma    | Server Type: HTTP
uptime-kuma    | Connecting to Database
uptime-kuma    | SQLite config:
uptime-kuma    | [ { journal_mode: 'wal' } ]
uptime-kuma    | [ { cache_size: -12000 } ]
uptime-kuma    | Connected
uptime-kuma    | Your database version: 9
uptime-kuma    | Latest database version: 9
uptime-kuma    | Database no need to patch
uptime-kuma    | Database Patch 2.0 Process
uptime-kuma    | patch-setting-value-type.sql is already patched, skip
uptime-kuma    | patch-improve-performance.sql is already patched, skip
uptime-kuma    | Load JWT secret from database.
uptime-kuma    | Adding route
uptime-kuma    | Adding socket handler
uptime-kuma    | Init the server
uptime-kuma    | Listening on 3001
uptime-kuma    | Latest Version: 1.6.0
```

**Comment by gaby** [comment]
This may be related to all the Pi4 issues with Docker... I can't run anything on my Pi4 either. There's conflics between the libraries bundled in Raspberry Pi OS and tbe `buster-updates` repo.

**Comment by louislam** [comment]
Ops, my pi4 will be arrived next week, at this moment, please use alpine one.

**Comment by louislam** [comment]
My Pi is arrived. Turns out I just forgot to also change the image of second stage to buster too. 

1.6.2 should be available soon. 

https://github.com/louislam/uptime-kuma/commit/ad2062713c1d2acddc6d8365c46d94ca811ae931

**Comment by gaby** [comment]
> My Pi is arrived. Turns out I just forgot to also change the image of second stage to buster too.
> 
> 1.6.2 should be available soon.
> 
> [ad20627](https://github.com/louislam/uptime-kuma/commit/ad2062713c1d2acddc6d8365c46d94ca811ae931)

Nice catch!
