### ISSUE TITLE
Nextcloud Talk notifications returning 400 Bad Request (self-hosted server)

### ISSUE THREAD

**Issue by Teyk0o** [louislam/uptime-kuma#6445]
### ⚠️ Please verify that your question has not already been reported

- [x] I have searched the [existing issues](https://github.com/louislam/uptime-kuma/issues?q=is%3Aissue%20sort%3Acreated-desc%20) and found no similar reports.

### 🛡️ Security Policy

- [x] I have read and agree to Uptime Kuma's [Security Policy](https://github.com/louislam/uptime-kuma/security/policy).

### 📝 Describe your problem

Hi 👋

I’m having an issue with the Nextcloud Talk integration: every time I click “Test Notification” in Uptime-Kuma, the request fails with a 400 Bad Request response from my server.

### 📝 Error Message(s) or Log

```bash session
Error: AxiosError: Request failed with status code 400
<html>
<head><title>400 Bad Request</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

### 🐻 Uptime-Kuma Version

2.0.1

### 💻 Operating System and Arch

Debian GNU/Linux 12 (Bookworm) - x86_64

### 🌐 Browser

All

### 🖥️ Deployment Environment

* **Runtime Environment**:

  * Docker: **Not used**
  * Docker Compose: **Not used**
  * Node.js: **v22.21.0**
  * Reverse Proxy: **Nginx 1.22.1**
  * Nextcloud Talk Bot endpoint: Hosted on a separate remote server
  * Talk : 21.1.5
  * Nextcloud : 31.0.11

* **Database**:

  * **SQLite (embedded)** (default Uptime-Kuma setup)

**Comment by louislam** [comment]
I think #6158 is well tested, and the 400 error is coming from nginx, not nextcloud talk. It may not be a bug.

You may need to provide more information here, like the notification config.

**Comment by Teyk0o** [comment]
> I think [#6158](https://github.com/louislam/uptime-kuma/pull/6158) is well tested, and the 400 error is coming from nginx, not nextcloud talk. It may not be a bug.
> 
> You may need to provide more information here, like the notification config.

Thanks for your answer!

You're right that the 400 error is coming from nginx somewhere in the request chain.
What’s strange in my case is that:

* My Nextcloud instance is hosted on a **different remote server**
* No logs appear on the Nextcloud server when I trigger the test from Uptime-Kuma
* curl requests to the same Talk bot URL work correctly
* The 400 only happens when triggered from Uptime-Kuma, not when testing manually

To help further, I’ve attached a screenshot of my **notification configuration**.


<img width="478" height="437" alt="Image" src="https://github.com/user-attachments/assets/b369ad60-719d-4b3d-b03b-697e86c5667d" />

**Comment by CommanderStorm** [comment]
> When nginx returns 400 (Bad Request) it will log the reason into error log, at "info" level. Hence an obvious way to find out what's going on is to configure [error_log](https://nginx.org/en/docs/ngx_core_module.html#error_log) to log messages at "info" level and take a look into error log when testing

https://stackoverflow.com/q/12315832/8927366

Could you try this?

**Comment by jcjveraa** [comment]
_Nevermind my previous comment, I now see UK uses GH issues for "help discussions" as well instead of using a forum - my input was that I'm Nextcloud Talk and it seems to work perfectly fine out of the box on Nextcloud v31, so that this wasn't a UK bug - but then this is not a bug report so that wasn't a very useful contribution from me :)_

**Comment by CommanderStorm** [comment]
Thanks

**Comment by JC-os** [comment]
Hello and thank you very much for your great software.
Uptime Kuma is surely an easy-to-use self-hosted monitoring tool.

While I was configuring Nextcloud Talk notifications, I got stuck in a 401 error.
I would like to share with you and the community how I did fix the problem.

First I followed your instructions gently included in the notification configuration popup.

~~~
# Setup bot
occ talk:bot:install \
    --feature response --no-setup \
    "Uptime Bot" "Secret" \
    https://uptime.domain.invalid

# Obtain BotId
occ talk:bot:list

# Add bot to a conversation
occ talk:bot:setup <BotId> <ConversationToken>
~~~

> This was leading me to a 401 error.

I see this error in nc log which might be the cause.

~~~
Errore / spreed
RequestExceptioncURL error 1: Protocol "responseonly" not supported (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for responseonly://a06048148b9524208688f316be08ffd8
Bot error occurred, increasing error count
~~~

Another indication is that I am using nextcloud 32 with High Performance Backend Talk 2.1.0~docker.

> Searching the internet I found this post: https://help.nextcloud.com/t/integrating-uptime-kuma-v2-with-nextcloud-talk-nextcloud-aio/241428

So my new setup was this one:
~~~
# Setup bot
occ talk:bot:create "Uptime Kuma Bot"

After running the command, Nextcloud will:
- create a new Talk bot
- automatically generate a secure secret token

Example output:
Bot created successfully
Bot ID: 16
Secret: 3cfa8b8c5e4e1f7b7d2c2a0c0a9c0e4f7c8a3b9e2d1c6f5a4b3c2d1e0f9a8b7

# Check that the bot has been succesfully created
occ talk:bot:list

# Add bot to a conversation
occ talk:bot:setup <BotId> <ConversationToken>
~~~

> This worked

Actually, I don't know if this is the nextcloud 32 change...
But anyway, I send this message to you if you would like to quote the article or update your integrated guide in kuma.
If you would like me to write a markdown guide using this article as a template I would be more than happy to do it for you.
Best regards.
Joseph.

**Comment by Teyk0o** [comment]
Sorry for the late response : I fixed the problem by manually adding "https://" before the host/domain.

**Comment by JC-os** [comment]
> Sorry for the late response : I fixed the problem by manually adding "https://" before the host/domain.

Thank you @Teyk0o that was ok for the 400 error but did not fix the 401 error. 

*I've cancelled the precedent message as everything is fine with that setup.*
