### ISSUE TITLE
Uptime less than 100% but no 'down' recorded

### ISSUE THREAD

**Issue by mwild1** [louislam/uptime-kuma#688]
**Is it a duplicate question?**
Not that I can find.

**Describe the bug**
I have a couple of services reporting uptimes such as "99.93%", but when I look in the dashboard the service is reported as never being down.

**To Reproduce**
Unknown. I have suspicions that it is maybe related to retries. Is it possible that a failed check is factored into the uptime calculation, even if a retry of that check succeeds?

**Expected behavior**
A service that never went down should have an uptime of 100%.

**Info**
Uptime Kuma Version: 1.7.3 (I shall upgrade soon, but I did not see any relevant fixes in the change log for 1.8.0)
Using Docker?: Yes
Docker Version: 19.03.13
OS: Debian
Browser: Firefox

**Comment by mwild1** [comment]
> If monitor switch to pending, then uptime percentage is decreased.

This "pending" status doesn't seem to be logged in the dashboard (or visible anywhere in the front-end I can see).

> If Your monitor changed status to pending, that means something was wrong for a heartbeat.

It's frustrating to know "something was wrong for a heartbeat", but with no indication to see when that was.

The reason I enabled retries is that a single failure doesn't necessarily mean that the target service is down - it's possible for the connection path between the monitor and the target to have >0.00% packet loss, and for that not to mean a problem with the service itself. Being able to monitor from multiple locations would be the ideal way to improve accuracy, but a simple retry is an acceptable fallback for now to discover if the service is unavailable.

**Comment by louislam** [comment]
> If monitor switch to pending, then uptime percentage is decreased. Monitor doesn't have to change status all way to down to lose uptime percentage. It should go back to 100% over time.
> 
> I would not describe this as a bug. If Your monitor changed status to pending, that means something was wrong for a heartbeat.

Correct. But I agree that the presentation is not good enough in the case.

**Comment by kzshantonu** [comment]
Push type monitor here. It's a very weird representation indeed. Last 30 day uptime is around 50%, but downtime is  [nowhere close to that](https://i.horizon.pics/KSO9xIssBW?k=T63CzRnpikHsqCHQ)

**Comment by chakflying** [comment]
Push type monitor has a specific bug fixed in #1627. For other types there might be other slight issues but I'm not sure.

**Comment by FliKites** [comment]
Any plans to handle this better?

**Comment by frankang** [comment]
Same to the ping monitor, my destination host sometimes has a 50% packet loss, but still showing 100% or 99%+ healthy record in uptime kuma. I guess it records when all 10 ping packets sent fail.

**Comment by seeingrain** [comment]
> Same to the ping monitor, my destination host sometimes has a 50% packet loss, but still showing 100% or 99%+ healthy record in uptime kuma. I guess it records when all 10 ping packets sent fail.

Yes, I'm sufferring from a bad ping with 50% packet loss too, but the ping monitor just report nice pings.
