### ISSUE TITLE
[Status Page] Let public users to change the theme

### ISSUE THREAD

**Issue by jahway603** [louislam/uptime-kuma#708]
**Is it a duplicate question?**
No

**Is your feature request related to a problem? Please describe.**
It is related to usability

**Describe the solution you'd like**
For an option to toggle Dark mode on/off on the user facing status page.

**Describe alternatives you've considered**
No alternatives available

**Additional context**
N/A

**Comment by mindlesstux** [comment]
I assume you are wanting a user/guest toggle and not admin style toggle?

**Comment by louislam** [comment]
Sorry for kept changing the tag, because the title and comments is a bit confused me, lol.

> However the dashboard page, even when you set it to dark theme, its only for that session.
It is by design.

**Comment by stefangrosaru** [comment]
I would personally find this sort of feature useful and perhaps other people that have a use case similar to mine:

In my use case I redirect users from my SPA to a separate subdomain where uptime-kuma is served. My SPA has light/dark mode and the user can switch between either. It would be very useful if a variable could be passed to uptime-kuma via the URL and that would set the theme for uptime-kuma.

**Comment by marvinruder** [comment]
A possible workaround to provide a light or dark themed status page to users based on their preferences (defined in the browser or the operating system) would be to use the “Custom CSS” field:
```
@media (prefers-color-scheme: dark) {
  body {
    background-color: rgb(9, 12, 16);
    color: rgb(177, 184, 192);
  }
  .monitor-list {
    background-color: rgb(13, 17, 23);
  }
  .monitor-list .item:hover {
      background-color: rgb(7, 10, 16);
  }
  a {
    color: rgb(177, 184, 192);
  }
  .badge {
    color: rgb(2, 11, 5);
  }
}
```

**Comment by johan-smits** [comment]
@marvinruder uour CSS did not did the trick. Why does it not switch like auto in in the dashboard?

**Comment by jahway603** [comment]
> I agree with the above. I don't really even see a need for there to be a toggle, the public status pages should just respect the browser's preference by default.

Unfortunately, not all browsers are created equally and this does not always work. The addition of a toggle on the public facing side where a user can change the theme is an accessibility issue & why I opened the issue in the first place.

**Comment by CommanderStorm** [comment]
@jahway603 
This is currently in 1.22:
![image](https://github.com/louislam/uptime-kuma/assets/26258709/23a9adbf-2206-4a81-9d14-0b2082d55adb)

Can you close this issue, since it is resolved?

**Comment by chakflying** [comment]
Currently, even when set to "auto", public non-logged in users still have to force theme change by changing the browser theme, which the author argued above as an inferior option. I understand and respect that, I think we can keep this open for now.

**Comment by louislam** [comment]
Yes, public users still cannot change the theme, it should not be closed yet.
