### ISSUE TITLE
No down notifications for push monitor

### ISSUE THREAD

**Issue by kaysond** [louislam/uptime-kuma#922]
### ⚠️ Please verify that this bug has NOT been raised before.

- [X] I checked and didn't find similar issue

### 🛡️ Security Policy

- [X] I agree to have read this project [Security Policy](https://github.com/louislam/uptime-kuma/security/policy)

### Description

I have a push monitor configured for a 1min interval. It appears that since upgrading, it no longer sends notification for missed heartbeats:
![image](https://user-images.githubusercontent.com/1147328/141818960-eba9f9bd-fad8-4a17-8457-5c18ddfa5b12.png)

You'll notice that between 8:14 and 8:21 there were no pings, but no down notifications were sent either.

I wonder if it has something to do with the failed SMTP notifications shown in the logs below, but I have the same issue on all my monitors and those send the gotify notifications just fine

### 👟 Reproduction steps

Configure a push monitor as below:
![image](https://user-images.githubusercontent.com/1147328/141819268-b83c0884-3d00-480b-aeff-bfed8e43c09f.png)

Ping the URL every minute for a while
Stop pinging the URL

### 👀 Expected behavior

Get a down notification

### 😓 Actual Behavior

Only get up notifications

### 🐻 Uptime-Kuma Version

1.10.2

### 💻 Operating System and Arch

Docker on Ubuntu 20.04

### 🌐 Browser

Firefox

### 🐋 Docker Version

20.10.10, build b485636

### 📝 Relevant log output

```shell
onitor #21 'Backups': Failing: No heartbeat in the time window | Interval: 60 seconds | Type: push
Cannot send notification to SMTP
Monitor #21 'Backups': Failing: No heartbeat in the time window | Interval: 60 seconds | Type: push
Cannot send notification to SMTP
Monitor #21 'Backups': Failing: No heartbeat in the time window | Interval: 60 seconds | Type: push
Cannot send notification to SMTP
Monitor #21 'Backups': Failing: No heartbeat in the time window | Interval: 60 seconds | Type: push
Cannot send notification to SMTP
Monitor #21 'Backups': Failing: No heartbeat in the time window | Interval: 60 seconds | Type: push
Cannot send notification to SMTP
Monitor #21 'Backups': Failing: No heartbeat in the time window | Interval: 60 seconds | Type: push
Cannot send notification to SMTP
Monitor #21 'Backups': Failing: No heartbeat in the time window | Interval: 60 seconds | Type: push
Cannot send notification to SMTP
Monitor #21 'Backups': Failing: No heartbeat in the time window | Interval: 60 seconds | Type: push
Cannot send notification to SMTP
Monitor #21 'Backups': Failing: No heartbeat in the time window | Interval: 60 seconds | Type: push
Cannot send notification to SMTP
Monitor #21 'Backups': Failing: No heartbeat in the time window | Interval: 60 seconds | Type: push
Cannot send notification to SMTP
Monitor #21 'Backups': Failing: No heartbeat in the time window | Interval: 60 seconds | Type: push
Cannot send notification to SMTP
```

**Comment by nbvcxz** [comment]
I got probably another issue, also with this kind of sensors, so it can be related somehow: My push notification is keep in `Pending` state (I expect `Failed` state after one pending), although there are no signals in set interval. No notification is being sent.
```
Monitor #27 'Home - AP2': Pending: No heartbeat in the time window | Max retries: 1 | Retry: 1 | Retry Interval: 60 seconds | Type: push
…
…
Monitor #27 'Home - AP2': Pending: No heartbeat in the time window | Max retries: 1 | Retry: 1 | Retry Interval: 60 seconds | Type: push
```
In my case, it seems it's still `Retry: 1` - I'm not sure, but it looks like it isn't counting retries.

**Comment by louislam** [comment]
Usually your smtp block the down mail for unknown reason.

Search this repo for more info. I remember someone had same problem with you.

**Comment by kaysond** [comment]
@louislam the problem is that i don't get a down notification to gotify either
smtp doesnt work for any other monitor either, but i get the gotify notifications for those
only the push monitor doesnt work

**Comment by louislam** [comment]
Just test it again, I still cannot reproduce your problem. Not quite sure what is missing here.

**Comment by kaysond** [comment]
Not sure what the issue was before, but restarting the container seems to have fixed it. Closing for now...
![image](https://user-images.githubusercontent.com/1147328/142478946-ff6c16f4-d0ef-4470-bb14-6c759da33c9e.png)

**Comment by kaysond** [comment]
@louislam there definitely seems to be some kind of issue with the push monitor logic that allows it to get into a bad state. It went down, then came back up, and now its spamming me with Up notifications every time it gets a ping...

I'm calling the url: `api/push/7oxXeSwthj?msg=OK&ping=$PING`

![image](https://user-images.githubusercontent.com/1147328/143492114-56f820c4-5c2d-4cde-bb9b-d98a4eefed9a.png)
![image](https://user-images.githubusercontent.com/1147328/143492329-b657e25e-0532-4594-a469-c13c7383f49d.png)

**Comment by kaysond** [comment]
Also not sure why there are gaps in the graph...

**Comment by chakflying** [comment]
Gaps are either a pending beat or a single up beat that is not connected as a line. I think this suggests that somehow more than 1 beat is produced every minute, which would be consistent with your observation that notification is constantly getting triggered, which would happen on every down-to-up transition.

**Comment by kaysond** [comment]
Is there a way to log the raw http requests so I can see exactly what's coming through? The cron job is set to ping every minute...

**Comment by hansenc0705** [comment]
I seem to be having this issue as well. I setup a new PUSH monitor and before i triggered my first GET to the URL i did get a down alert, triggered my GET to the URL and got an up alert then I didn't trigger another GET to the URL and haven't received an alert but can see in the WebUI that its down but the history doesn't call it out.

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/10247644/143691242-61bbe8c2-45c8-4068-a1d2-71e517dc15ef.png">

**Comment by louislam** [comment]
Finally addressed the issue, it should be fixed in the next release

**Comment by hansenc0705** [comment]
This might still be broken, I am no longer receiving down alerts if I intentionally stop the job hitting the URL. The monitor still says up.

**Comment by robjuffermans** [comment]
I'm using matrix for the notifications and only receive the UP notifications, no DOWN. Using version 1.11.1 in docker.

**Comment by hansenc0705** [comment]
I'm not sure if we should crate a new issue or if @louislam can reopen this one?

**Comment by robjuffermans** [comment]
> I'm using matrix for the notifications and only receive the UP notifications, no DOWN. Using version 1.11.1 in docker.

this is fixed in 1.11.3! Thanks!

**Comment by louislam** [comment]
> > I'm using matrix for the notifications and only receive the UP notifications, no DOWN. Using version 1.11.1 in docker.
> 
> this is fixed in 1.11.3! Thanks!

It should not be related, the logic is the same as 1.11.1.

> I'm not sure if we should crate a new issue or if @louislam can reopen this one?

I remember that I tested it a month ago, it should be working, but it could possibly be another hidden issue.

If you find a way to reproduce the issue, feel free to open a new issue.

**Comment by kaysond** [comment]
Something really bad is still happening. Note that its going down and up within the same second... 
I just updated to the latest version again I'll report back if I still see the problem.
![image](https://user-images.githubusercontent.com/1147328/151106797-17fb9667-8a7c-4524-b71b-d22d50343c15.png)

**Comment by kaysond** [comment]
@louislam fyi - still a problem as of  `1.11.3`. Going to try `1.12.1`
![image](https://user-images.githubusercontent.com/1147328/157148347-6fb648ca-9e59-4479-9bb2-b538eaeef51d.png)

**Comment by louislam** [comment]
I think maybe there is a hidden issue. Let me know if anyone know how to reproduce.

**Comment by hansenc0705** [comment]
Try this @louislam - configure monitor, restart Uptime Kuma (might not be required), cause a failure and it will alert, bring service back up and it will go green. after that it will not detect future failures. Seems is always works on first failure after a restart of Uptime Kuma but after that first failure no more alerts.

**Comment by kaysond** [comment]
@louislam I think you might have a race condition. Or maybe a conditional that's not mutually exclusive.

If the ping happens exactly 60s after the last one, it causes both an `Up` and a `Down`. Interestingly, the other ones are technically correct because the ping comes 61s later.

Can you add a grace period? So if I set it to 60s, it will actually wait for 60s+1s, for example? (I know I can just set the checking to 60s, but its confusing because I have a cronjob set to run it every minute, and its just because the times aren't perfectly in sync + latency)

Here is my dashboard:
![image](https://user-images.githubusercontent.com/1147328/160219491-5d077488-49b8-4a77-99b4-7397873384f3.png)

And here are my http logs:
```
[25/Mar/2022:17:54:05 -0700]  "GET /api/push/xxxx?msg=OK&ping=92.177 HTTP/1.1" "-" "curl/7.74.0" TLSv1.3 TLS_AES_256_GCM_SHA384 200 5567
[25/Mar/2022:17:55:05 -0700] 9 "GET /api/push/xxxx?msg=OK&ping=92.196 HTTP/1.1" "-" "curl/7.74.0" TLSv1.3 TLS_AES_256_GCM_SHA384 200 5567
```

```
[25/Mar/2022:17:58:05 -0700] "GET /api/push/xxx?msg=OK&ping=90.552 HTTP/1.1" "-" "curl/7.74.0" TLSv1.3 TLS_AES_256_GCM_SHA384 200 5567
[25/Mar/2022:17:59:06 -0700]  "GET /api/push/xxx?msg=OK&ping=91.308 HTTP/1.1" "-" "curl/7.74.0" TLSv1.3 TLS_AES_256_GCM_SHA384 200 5567
```

**Comment by kaysond** [comment]
Yeah I was right. There is a race condition! You have the monitor running on a setTimeout that is totally independent of the call of the push URL. That means that `beat()` and `router.get("/api/push/:pushToken")` can both get called at the same time in seconds (e.g. both at 17:15:02), but if `beat()` happens first, it will mark the monitor as down, then it will immediately mark it as up when `router.get()` is run.

https://github.com/louislam/uptime-kuma/blob/12237dec6e3809404a1c84df394b232431b0f5f0/server/model/monitor.js#L309-L329

https://github.com/louislam/uptime-kuma/blob/12237dec6e3809404a1c84df394b232431b0f5f0/server/model/monitor.js#L468-L475

https://github.com/louislam/uptime-kuma/blob/12237dec6e3809404a1c84df394b232431b0f5f0/server/routers/api-router.js#L20-L84

The other issue (I think) is that the call to the push URL does not reset the setTimeout. So if, for example, `beat()` runs at 16:17:04, it will run again at 16:18:04, no matter what. But if I call the push URL at 16:17:05, I'll probably call it again at 16:18:05, which is 60s later - totally valid! But again, it will get marked as down then up 1s later.

I think the right thing to do, though it may be a little difficult with the way you have the architecture set up, is to do the first `setTimeout` on `monitor.start()`, but every other `setTimeout` should be run from `router.get("/api/push:pushToken")`. Also, the timeout probably needs to have an extra second, like `setTimeout(safebeat, (interval + 1)*1000)`. That way any push URL call in the entire 1s window of 16:17:04, for example, will keep the monitor "Up".

Let me know if you have any questions!

**Comment by scr4tchy** [comment]
This is still relevant. My PUSH sensors are only sending `DOWN` notifications to Discord, and not thé `UP`. While the status goes back to `UP` in the chart & the bars, the history does not record the `UP` state and no notification goes through. This persists after reboot of the application, after deleting all the events/heartbeats of the probe. What’s more is that I don’t feel like the retries / interval works as expected - with 3 retries, 60 in the interval values & pushes sent every 60sec, I get notified as soon as a single push is sent with `DOWN` - shouldn’t it be after 3?

**Comment by kaysond** [comment]
@scr4tchy this particular issue was definitely fixed. Can you try running v[1.17.1](https://github.com/louislam/uptime-kuma/releases/tag/1.17.1) and see if things work as expected? If they do, it's a regression.

**Comment by scr4tchy** [comment]
![image](https://user-images.githubusercontent.com/873014/221305330-b966a866-7cbb-4530-b774-0583c88bd121.png)

### docker-compose.yml
```
version: '3.3'
services:
  status:
    image: louislam/uptime-kuma:1.17.1-alpine
    container_name: status
    restart: unless-stopped
    volumes:
      - ./data/status:/app/data
```

### main.py
```
import asyncio
import aiohttp
import yaml
from datetime import datetime, timedelta

async def check(check, cfg, session):
    # Check
    t = datetime.now()
    try:
        async with session.get(url=check["url"]) as resp:
            status = "up" if resp.status == 200 else "down"
            msg = str(resp.status)
    except Exception as e:
        status = "down"
        msg = "EXCEPT"
        print("Unable to get url {} due to {}.".format(check["url"], e.__class__))
    dt = (datetime.now() - t).total_seconds()

    # Push
    try:
        await session.get(url="{}/{}?status={}&ping={}&msg=OK".format(cfg["push_url"], check["id"], status, dt))
    except Exception as e:
        print("Unable to push status due to {}".format(e.__class__))

async def main():
    # Load config
    with open("./config.yaml", 'r') as f:
        cfg = yaml.load(f, Loader=yaml.FullLoader)

    # Loop
    while True:
        t_next = datetime.now() + timedelta(seconds=30)

        async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=10)) as session:
            await asyncio.gather(*[check(c, cfg, session) for c in cfg["checks"]])

        # Wait until next interval.
        print("Sleeping until %s" % t_next)
        await asyncio.sleep((t_next - datetime.now()).total_seconds())

asyncio.run(main())
```

### config.yaml
```
push_url: https://status.xxx.xx/api/push
checks:
  - id: <id>
    url: http://service:8080
```

**Comment by scr4tchy** [comment]
![image](https://user-images.githubusercontent.com/873014/221309633-fc40c6a5-5d73-4572-b139-8632b942ecc4.png)

```
import asyncio
import aiohttp
import yaml
from datetime import datetime, timedelta

async def check(check, cfg, session):
    # Check
    t = datetime.now()
    try:
        async with session.get(url=check["url"]) as resp:
            status = "up" if resp.status == 200 else "down"
            msg = str(resp.status)
    except Exception as e:
        status = "down"
        msg = "EXCEPT"
        print("Unable to get url {} due to {}.".format(check["url"], e.__class__))
    dt = (datetime.now() - t).total_seconds()

    # Push
    try:
        await session.get(url="{}/{}?status={}&ping={}&msg={}".format(cfg["push_url"], check["id"], status, dt, msg))
    except Exception as e:
        print("Unable to push status due to {}".format(e.__class__))

async def main():
    # Load config
    with open("./config.yaml", 'r') as f:
        cfg = yaml.load(f, Loader=yaml.FullLoader)

    # Loop
    while True:
        t_next = datetime.now() + timedelta(seconds=30)

        async with aiohttp.ClientSession(timeout=aiohttp.ClientTimeout(total=10)) as session:
            await asyncio.gather(*[check(c, cfg, session) for c in cfg["checks"]])

        # Wait until next interval.
        print("Sleeping until %s" % t_next)
        await asyncio.sleep((t_next - datetime.now()).total_seconds())

asyncio.run(main())
```

It might've been due to pushing heartbeats continuously, with `status=up`,  `status=down` during downtime and then `status=up` again as soon as the service went back up. It would send notifications every single time a `status=down` was received, ignoring the retry configuration, and would never send a notification once up again. Skipping pushes during downtime may be fixing it, as I tested it once and didn't receive duplicated but did receive an up notification.

**Comment by kaysond** [comment]
Yeah this is unrelated to this issue then. I believe the retry only applies if the heartbeat is missed completely. Similarly, it probably sends a notification on every down heartbeat on purpose. But if you can send multiple down heartbeats, I'm not sure why you need uptime-kuma at all...

**Comment by Electron707** [comment]
I know this issue is closed; but i am having similar issue on the 2.0.2 version; where TEST notification do work, but when actual status change of the site goes down then the notificaiton does not go through.
I am using ntfy as the notification service.
